name:     "ElementsMultiFade"

exports:  "ElementsMultiFade.js"

author:   "subhaze"

category: "Effects"

tags:     "[navigation, tween, element, effects]"

demo:     "http://mootools.net/shell/JZVZA/"

current: "v1.0"

sources:
  - "Source/Elements.MultiFade.js"