name:     "ElementsMultiFade"

exports:  "ElementsMultiFade.js"

author:   "subhaze"

category: "Effects"

tags:     "[navigation, tween, element, effects]"

demo:     "http://www.jsfiddle.net/subhaze/v3p86/"

current: "v1.2"

sources:
  - "Source/Elements.MultiFade.js"